# Generated by Django 6.0.6 on 2026-07-27 08:41

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0016_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Ghidora Transport', max_length=150)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=payments.models.qr_upload_path)),
                ('upi_id', models.CharField(blank=True, help_text='e.g. ghidoratransport@upi', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('default_advance_percentage', models.PositiveSmallIntegerField(default=30, help_text='Default % of fare requested as advance.')),
                ('payment_deadline_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours before an unpaid request expires.')),
                ('reminder_hours', models.CharField(default='6,12', help_text='Comma separated hours (before deadline expiry) to send reminders.', max_length=50)),
                ('payment_instructions', models.TextField(blank=True, default='Please complete the payment using any of the methods below and upload proof of payment for verification.')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=150)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=150)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=150)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=150)),
                ('cashfree_app_id', models.CharField(blank=True, max_length=150)),
                ('cashfree_secret_key', models.CharField(blank=True, max_length=150)),
                ('active_gateway', models.CharField(choices=[('manual', 'Manual Verification'), ('razorpay', 'Razorpay'), ('phonepe', 'PhonePe Gateway'), ('gpay', 'Google Pay Gateway'), ('cashfree', 'Cashfree'), ('stripe', 'Stripe')], default='manual', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('advance', 'Advance Payment'), ('remaining', 'Remaining Payment'), ('custom', 'Custom Amount')], default='advance', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_already_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Payment Submitted'), ('waiting_verification', 'Waiting Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=25)),
                ('due_date', models.DateTimeField()),
                ('preferred_method', models.CharField(blank=True, choices=[('qr', 'QR Code'), ('upi', 'UPI ID'), ('bank', 'Bank Transfer')], help_text='Method the customer ultimately chose (set on proof submission).', max_length=10)),
                ('gateway', models.CharField(choices=[('manual', 'Manual Verification'), ('razorpay', 'Razorpay'), ('phonepe', 'PhonePe Gateway'), ('gpay', 'Google Pay Gateway'), ('cashfree', 'Cashfree'), ('stripe', 'Stripe')], default='manual', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=150)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=150)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='booking.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_used', models.CharField(choices=[('qr', 'QR Code'), ('upi', 'UPI ID'), ('bank', 'Bank Transfer')], max_length=10)),
                ('screenshot', models.FileField(upload_to=payments.models.payment_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf'])])),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('upi_app_used', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_approved', 'Booking Approved'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('payment_rejected', 'Payment Rejected'), ('receipt_ready', 'Receipt Ready'), ('driver_assigned', 'Driver Assigned'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('payment_reminder', 'Payment Reminder'), ('booking_expired', 'Booking Expired')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Payment Submitted'), ('waiting_verification', 'Waiting Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('completed', 'Completed')], max_length=25)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.paymentrequest')),
            ],
            options={
                'verbose_name_plural': 'Payment status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reupload_requested', 'Re-upload Requested')], max_length=25)),
                ('rejection_reason', models.CharField(blank=True, choices=[('wrong_screenshot', 'Wrong Screenshot'), ('amount_mismatch', 'Amount Mismatch'), ('fake_screenshot', 'Fake Screenshot'), ('blur_image', 'Blur / Unreadable Image'), ('duplicate_transaction', 'Duplicate Transaction'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verifier_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('proof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='payments.paymentproof')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=payments.models.receipt_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.paymentrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentproof',
            constraint=models.UniqueConstraint(fields=('transaction_id',), name='unique_transaction_id'),
        ),
    ]
