# Generated by Django 6.0.6 on 2026-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentproof',
            name='unique_transaction_id',
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='method_used',
            field=models.CharField(choices=[('qr', 'QR Code'), ('upi', 'UPI ID'), ('bank', 'Bank Transfer')], default='upi', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='preferred_method',
            field=models.CharField(blank=True, choices=[('qr', 'QR Code'), ('upi', 'UPI ID'), ('bank', 'Bank Transfer')], help_text='Method the customer ultimately chose.', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='reminder_hours',
            field=models.CharField(default='6,12', help_text='Comma separated hours before deadline expiry to send reminders.', max_length=50),
        ),
    ]
