# Generated by Django 6.0.6 on 2026-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='occasion_posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
