"""
Django settings for ghidora_transport project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-07kifmlf3r+js5e00dp@1#old47f6cjudsc0a@lq1mb&c*p$i%'
)

DEBUG = True

# 🌟 Allow all hosts (Mobile, Ngrok, Local Network, Render)
ALLOWED_HOSTS = ['*']

# 🌟 CSRF Fix for Ngrok, Local Network & Render Deployment
CSRF_TRUSTED_ORIGINS = [
    'https://ghidoratransport.onrender.com',
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'http://*.ngrok-free.dev',
    'http://*.ngrok-free.app',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://192.168.*.*',
    'http://10.*.*.*',
]

# Disable cookie secure enforcement for local dev / ngrok HTTP
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',                          # Required by allauth

    'allauth',                                        # Allauth
    'allauth.account',                                # Account
    'allauth.socialaccount',                          # Socialaccount
    'allauth.socialaccount.providers.google',         # Google login provider

    'booking',
    'drivers',
    'chatbot',
    'expenses',
    'occasions',
    'quotations',
    'social',
    'payments',
]

SITE_ID = 1  # Required by django.contrib.sites / allauth

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',   # Required by allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ghidora_transport.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'occasions.context_processors.active_occasion',
            ],
        },
    },
]

WSGI_APPLICATION = 'ghidora_transport.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "booking/static",
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================================
# Email Configuration (Gmail)
# ================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ghidoratransport@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'xmcqcdadvdljbypx')
DEFAULT_FROM_EMAIL = 'Ghidora Transport <ghidoratransport@gmail.com>'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ================================
# OpenRouteService (Distance API)
# ================================
ORS_API_KEY = os.environ.get(
    'ORS_API_KEY',
    'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjM1MjMyY2Q2MjU1OTRmMTZhYmY5OGIzOTE0YzQ3NGQ1IiwiaCI6Im11cm11cjY0In0='
)

# ================================
# Google Gemini (AI Chatbot / Occasion Messages)
# ================================
GEMINI_API_KEY = os.environ.get(
    'GEMINI_API_KEY',
    'yahan-apni-gemini-api-key-paste-karo'
)

# ================================
# Google Maps Platform API Key
# ================================
GOOGLE_MAPS_API_KEY = os.environ.get(
    'GOOGLE_MAPS_API_KEY',
    ''
)

# ================================
# Login redirect settings
# ================================
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ================================
# django-allauth / Google Login settings
# ================================
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
SOCIALACCOUNT_LOGIN_ON_GET = True