# Generated by Django 6.0.6 on 2026-07-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_booking_assigned_driver'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Per Trip', 'Per Trip'), ('Monthly Salary', 'Monthly Salary')], default='Per Trip', max_length=20)),
                ('month', models.CharField(blank=True, help_text="Sirf 'Monthly Salary' ke liye - jaise 'July 2026'", max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text="Sirf 'Per Trip' payment ke liye - kaunsi booking ke liye ye payment hai", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_payments', to='booking.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField(help_text='Kitne liter diesel bhara')),
                ('rate_per_liter', models.FloatField(help_text='Us din ka diesel rate per liter')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_expenses', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Engine Oil Change', 'Engine Oil Change'), ('Tyre Replacement', 'Tyre Replacement'), ('Brake Service', 'Brake Service'), ('General Service', 'General Service'), ('Repair', 'Repair'), ('Other', 'Other')], default='General Service', max_length=30)),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='drivers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TollParkingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll', models.FloatField(default=0)),
                ('parking', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('other_note', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_expenses', to='booking.booking')),
            ],
        ),
    ]
