# Generated by Django 6.0.6 on 2026-07-09 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number 10 digits ka hona chahiye (e.g. 9876543210)', regex='^[6-9]\\d{9}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('status', models.CharField(choices=[('available', '🟢 Available'), ('busy', '🔴 Busy')], default='available', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Naye bookings me is driver ko automatically assign kiya jayega, jab tak admin khud koi aur driver na choose kare.', verbose_name='Default Driver (auto-assign)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='e.g. CG05 AB 1234', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(help_text='e.g. Mahindra Pickup / Mini Truck', max_length=100)),
                ('capacity', models.CharField(help_text='e.g. 1 Ton', max_length=50)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='drivers/vehicles/')),
                ('rc_number', models.CharField(max_length=30)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail', to='drivers.driver')),
            ],
        ),
    ]
