# Generated by Django 6.0.6 on 2026-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Tata Ace', 'Tata Ace'), ('Pickup', 'Pickup'), ('Bolero Pickup', 'Bolero Pickup'), ('Mini Truck', 'Mini Truck'), ('Tractor Trolley', 'Tractor Trolley')], default='Tata Ace', max_length=30),
        ),
    ]
