# Generated by Django 6.0.6 on 2026-06-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Tata Ace', 'Tata Ace'), ('Pickup', 'Pickup'), ('Bolero Pickup', 'Bolero Pickup'), ('Mini Truck', 'Mini Truck'), ('Tractor Trolley', 'Tractor Trolley'), ('Mahindra Bolero', 'Mahindra Bolero'), ('Mahindra Cruiser', 'Mahindra Cruiser'), ('Magic', 'Mahindra Jeeto Magic'), ('Van', 'Van'), ('Mini Bus', 'Mini Bus')], default='Tata Ace', max_length=30),
        ),
    ]
