# Generated by Django 6.0.6 on 2026-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Mahindra Pickup', 'Mahindra Pickup'), ('Mahindra Bolero', 'Mahindra Bolero'), ('Mahindra Cruiser', 'Mahindra Cruiser'), ('Magic', 'Mahindra Jeeto Magic'), ('Van', 'Van'), ('Mini Bus', 'Mini Bus'), ('Tata Ace', 'Tata Ace'), ('Mini Truck', 'Mini Truck'), ('Tractor Trolley', 'Tractor Trolley')], default='Mahindra Pickup', max_length=30),
        ),
    ]
