# Generated by Django 6.0.6 on 2026-06-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(default='One Way', max_length=20),
        ),
    ]
