# Generated by Django 6.0.6 on 2026-07-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance_source',
            field=models.CharField(choices=[('Google Generated', 'Google Generated'), ('Manual Entered', 'Manual Entered')], default='Manual Entered', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='toll_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='toll_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='toll_screenshots/'),
        ),
    ]
