# Generated by Django 6.0.6 on 2026-07-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cargo_type',
            field=models.CharField(blank=True, help_text='Customer kya transport karwana chahta hai', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, help_text='Customer ka free-text message', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton')], default='kg', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('voice', 'Voice Message'), ('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='booking_attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='booking.booking')),
            ],
        ),
    ]
