# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_reviewcomment_reviewlike_reviewshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedRouteFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(help_text='Pickup location name (e.g., Dhamtari)', max_length=100)),
                ('to_location', models.CharField(help_text='Destination location name (e.g., Raipur)', max_length=100)),
                ('fixed_fare', models.DecimalField(decimal_places=2, help_text='Fixed route fare in ₹', max_digits=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Inactive')),
                ('same_direction_both', models.BooleanField(default=False, help_text='If enabled, this fare applies for reverse direction (To -> From) as well.', verbose_name='Same fare for both directions')),
                ('description', models.TextField(blank=True, help_text='Optional note/description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predefined Route Fare',
                'verbose_name_plural': 'Predefined Route Fares',
                'ordering': ['from_location', 'to_location'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='fare_type',
            field=models.CharField(
                choices=[('Predefined Route Fare', 'Predefined Route Fare'), ('Distance Based Fare', 'Distance Based Fare'), ('Manual/Other', 'Manual/Other')],
                default='Distance Based Fare',
                help_text='Fare calculation method used for this booking',
                max_length=50
            ),
        ),
    ]
