# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_predefinedroutefare_booking_fare_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedroutefare',
            name='double_trip_fare',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Double trip / Round trip fixed route fare in ₹ (leave blank to auto-double single trip fare)',
                max_digits=10,
                null=True,
                verbose_name='Double Trip Fare (Round Trip ₹)'
            ),
        ),
        migrations.AlterField(
            model_name='predefinedroutefare',
            name='fixed_fare',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Single trip / One-way fixed route fare in ₹',
                max_digits=10,
                verbose_name='Single Trip Fare (One Way ₹)'
            ),
        ),
    ]
