# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_predefinedroutefare_double_trip_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedroutefare',
            name='distance_km',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Optional distance in KM for this route (e.g. 49.5). If set, this distance will be automatically filled for bookings.',
                max_digits=8,
                null=True,
                verbose_name='Route Distance (KM)'
            ),
        ),
    ]
