# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_predefinedroutefare_distance_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedRouteDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(help_text='Pickup location name (e.g., Kodebod)', max_length=100)),
                ('to_location', models.CharField(help_text='Destination location name (e.g., Raipur)', max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Fixed route distance in KM (e.g., 49.5)', max_digits=8, verbose_name='Distance (KM)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Inactive')),
                ('same_direction_both', models.BooleanField(default=True, help_text='If enabled, this distance applies for reverse direction (To -> From) as well.', verbose_name='Same distance for both directions')),
                ('description', models.TextField(blank=True, help_text='Optional note/description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predefined Route Distance',
                'verbose_name_plural': 'Predefined Route Distances',
                'ordering': ['from_location', 'to_location'],
            },
        ),
    ]
