# Generated by Django on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_predefinedroutedistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Destination Latitude'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Destination Longitude'),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Route Duration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Pickup Latitude'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Pickup Longitude'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='distance_source',
            field=models.CharField(choices=[('Google Generated', 'Google Generated'), ('Google Maps Route', 'Google Maps Route'), ('Manual Entered', 'Manual Entered')], default='Manual Entered', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(max_length=300),
        ),
    ]
