# Generated by Django 6.0.6 on 2026-08-13 06:39

import pickupwala.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shayari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Trucker slogan / shayari line shown on the signage board, e.g. 'देखो मगर प्यार से'", max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'Shayari',
                'verbose_name_plural': 'Shayaris',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('audio_file', models.FileField(help_text='mp3 / wav / m4a file', upload_to=pickupwala.models.song_audio_path)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cassette/cover art. If left blank the player shows the default cassette icon.', null=True, upload_to=pickupwala.models.song_cover_path)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text="Song length in seconds, used for the progress bar. Leave 0 and the player will fall back to the audio file's own length.")),
                ('trip_km', models.PositiveIntegerField(default=150, help_text="Distance shown on the road progress readout for this song (purely cosmetic, e.g. '150 km')")),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to remove from the live playlist without deleting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Playlist order, lower numbers play first')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
