# Generated by Django 6.0.6 on 2026-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickupwala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chai pe charcha! ☕', help_text="Title for Chai break popup, e.g. 'Chai pe charcha! ☕'", max_length=150)),
                ('message', models.CharField(default='Music baad mein, pehle chai!', help_text="Subtitle/message shown on Chai break popup, e.g. 'Music baad mein, pehle chai!'", max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'Chai Break Message',
                'verbose_name_plural': 'Chai Break Messages',
                'ordering': ['order', 'id'],
            },
        ),
    ]
