# Generated by Django 6.0.6 on 2026-07-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_booking_assigned_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pickup', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('goods_type', models.CharField(blank=True, max_length=150)),
                ('weight', models.CharField(blank=True, help_text='e.g. 500 KG', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('Mahindra Pickup', 'Mahindra Pickup'), ('Mahindra Bolero', 'Mahindra Bolero'), ('Mahindra Cruiser', 'Mahindra Cruiser'), ('Magic', 'Magic'), ('Van', 'Van'), ('Mini Bus', 'Mini Bus'), ('Tata Ace', 'Tata Ace'), ('Mini Truck', 'Mini Truck'), ('Tractor Trolley', 'Tractor Trolley')], default='Mahindra Pickup', max_length=30)),
                ('distance', models.FloatField(default=0)),
                ('base_fare', models.FloatField(default=0)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('quote_type', models.CharField(choices=[('Instant', 'Instant Estimate'), ('Custom', 'Custom Quotation')], default='Instant', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=10)),
                ('is_approved', models.BooleanField(default=False, help_text='Bade amount (₹50,000+) ke liye admin approval')),
                ('rejection_reason', models.CharField(blank=True, max_length=100)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='booking.booking')),
            ],
        ),
    ]
